
services:
  web:
    container_name: ${ODOO_CONTAINER_NAME}
    image: odoo:${ODOO_VERSION}
    build: .
    restart: always
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - odoo-web-school-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
  db:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:${PG_VERSION}
    restart: always
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - odoo-db-school-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-school-data:
  odoo-db-school-data:
  
  
  